-- GUEST BOOK DDL 

CREATE TABLE GUESTBOOK_MESSAGE (
    MESSAGE_ID int PRIMARY KEY auto_increment,
    GNAME VARCHAR(50) NOT NULL,
    GPASSWORD VARCHAR(20) NOT NULL,
    GMESSAGE TEXT NOT NULL
);

-- ORACLE 설정:
-- CREATE SEQUENCE GM_MID_SEQ START WITH 1 INCREMENT BY 1;

-- SELECT GM_MID_SEQ.nextval FROM guestbook_message;