-- GUEST BOOK DDL 

CREATE TABLE GUESTBOOK_MESSAGE (
    MESSAGE_ID NUMBER(6) CONSTRAINT GB_MID_PK PRIMARY KEY, --NOTNULL, UNIQUE 속성 포함 
    GNAME VARCHAR2(50) NOT NULL,
    GPASSWORD VARCHAR(20) NOT NULL,
    GMESSAGE BLOB NOT NULL
);  